feat: create a committedCart state item to keep track of committed co…
ethereum/clrfund pull request #134
Opened 2021-06-09 16:39 UTC by corwintines

https://github.com/ethereum/clrfund/issues/104

Testing cases:
- Make sure tallying phase still shows correct committed items
- Remove all cart items in reallocation, make sure tallying phase still shows correct committed items
- Edit cart but dont commit while in reallocation, make sure tallying phase still shows correct committed items
- Edit cart in reallocation phase, make sure tallying phase still shows correct committed items
- Refresh app, make sure tallying phase still shows correct committed items

2021-06-09 17:38 UTC, pettinarip commented on vue-app/src/components/Cart.vue
> +    }
Just a nice to have refactor: 

Maybe we could add a new method called `getCartTotal` to abstract the calculation and reuse it below. Like this:

```
getCartTotal(cart: Cart): BigNumber {
  const { nativeTokenDecimals, voiceCreditFactor } = this.$store.state.currentRound
  return cart.reduce((total: BigNumber, item: CartItem) => {
    let amount
    try {
      amount = parseFixed(item.amount, nativeTokenDecimals)
    } catch {
      return total
    }
    return total.add(amount.div(voiceCreditFactor).mul(voiceCreditFactor))
  }, BigNumber.from(0)) 
}
```
then, the `getTotal` would looks like this:
```
getTotal(): BigNumber {
  const { cart, committedCart, currentRound } = this.$store.state

  // In tally round, use the committedCart to get total contribution amount
  if (currentRound.status === RoundStatus.Tallying) {
    return this.getCartTotal(committedCart)
  }

  return this.getCartTotal(cart)
}
```

2021-06-09 20:19 UTC, samajammin requested changes
Looks great for the most part! A few small comments. Reviewed on mobile in between flights so didn't get to all of it.

2021-06-09 20:19 UTC, samajammin commented on vue-app/src/components/Cart.vue
> +    if (this.$store.state.currentRound.status === RoundStatus.Tallying) {
I think we'll want this for any round status beyond reallocation. I believe there's a "hasReallocationElapsed" getter or similar.

2021-06-09 20:19 UTC, samajammin commented on vue-app/src/components/Cart.vue
> +  LOAD_COMMITTED_CART_DISPATCH,
Let's go with "LOAD_COMMITTED_CART"

2021-06-09 20:19 UTC, samajammin commented on vue-app/src/components/Cart.vue
> +    if (this.$store.state.currentRound.status === RoundStatus.Tallying) {
Same here - update to any state after reallocation.

2021-06-09 21:31 UTC, corwintines commented on vue-app/src/components/Cart.vue
> +    }
Yeah good call.

2021-06-09 22:02 UTC, corwintines commented
@samajammin @pettinarip Took your change requests and put them in. Did a refactor of a mutation-type I put in that wouldnt be needed in the end after looking at Vue.set

2021-06-10 10:06 UTC, ryancreatescopy commented
This works as intended for me! Nice work @corwintines

2021-06-11 00:14 UTC, samajammin requested changes
Couple small changes.

Overall this looks good! I unfortunately haven't been able to go through the flow locally - I keep getting invalid hex string errors when attempting to contribute (https://github.com/ethereum/clrfund/issues/99).

Let's walk through this flow together on your machine tomorrow so we can get this merged.

2021-06-11 00:14 UTC, samajammin commented on contracts/scripts/deployTestRound.ts
> +    signUpDuration: 75,  // 5 minutes
```suggestion
    signUpDuration: 300,  // 5 minutes
```

2021-06-11 00:14 UTC, samajammin commented on contracts/scripts/deployTestRound.ts
> +    votingDuration: 75,
```suggestion
    votingDuration: 300,
```

2021-06-11 00:14 UTC, samajammin commented on vue-app/src/components/ContributionModal.vue
> +    this.$store.dispatch(SAVE_COMMITTED_CART_DISPATCH)
I believe this should only happen when on successful transactions

2021-06-11 00:14 UTC, samajammin commented on vue-app/src/components/ReallocationModal.vue
> +    this.$store.dispatch(SAVE_COMMITTED_CART_DISPATCH)
Same here - I believe this should only happen when on successful transactions

2021-06-11 00:15 UTC, samajammin commented
FYI @corwintines - I pushed up a small change so make sure you pull before making any commits.

2021-06-11 00:18 UTC, samajammin approved these changes
On 2nd thought, since @ryancreatescopy was able to successfully test interaction, I'm just going to make those small tweaks & merge so we can unblock @pettinarip.

Nice work @corwintines!

2021-06-11 00:18 UTC, merged