Moves metaInfo into router/index.ts [Closes #82]
ethereum/clrfund pull request #184
Opened 2021-07-01 22:16 UTC by wackerow

Assigns a metaInfo title to each view in `router/index.ts`, removing these from individual components.

Exception is `Project.vue` where it pulls name of project passed in path and assigns to metaInfo

2021-07-03 03:14 UTC, corwintines approved these changes

2021-07-03 03:14 UTC, corwintines commented on vue-app/src/router/index.ts
> +    path: '/about-sybil-attacks',
Good catch

2021-07-05 13:36 UTC, pettinarip requested changes
I was looking into `metaInfo` to see what was its purpose and I found that it didn't exist as is.

The config we want to use is called `meta`. https://router.vuejs.org/api/#route-object-properties

2021-07-13 23:46 UTC, pettinarip approved these changes

2021-07-14 02:44 UTC, merged