Rounded corners missing from round details container
ethereum/clrfund pull request #197
Opened 2021-07-10 03:21 UTC by corwintines

Fixes: https://github.com/ethereum/clrfund/issues/176

2021-07-12 22:38 UTC, corwintines reviewed
Just wanted to comment that originally I had tried to do overflow:hidden here, and it fixed the rounding problems better but then we got back to the tool tip being cutoff. So, I opted for this solution for now. Its not ideal, but I think in order to maintain the tooltip this will be best for now.

2021-07-13 02:25 UTC, pettinarip approved these changes

2021-07-14 20:43 UTC, wackerow requested changes
Would suggest using pseudo-selectors `:first-of-type` and `:last-of-type` like below instead of hard coding a class to the last div =)

```
.round-value-info {
  width: 100%;
  display: grid;
  align-items: center;
  margin-bottom: 3rem;
  border-radius: 0.5rem;

  & > div {
    box-shadow: inset 0px -1px 0px #7375a6;
    &:first-of-type {
      border-radius: 0.5rem 0.5rem 0 0;
    }
    &:last-of-type {
      border-radius: 0 0 0.5rem 0.5rem;
      box-shadow: none;
    }
  }
}
```

2021-07-14 21:12 UTC, corwintines reviewed
Looks good to me @wackerow . Thanks for sharing that, need to brush up on my css pseudo-selectors

2021-07-14 21:20 UTC, merged