Adds component getters for block explorer urls
ethereum/clrfund pull request #242
Opened 2021-08-06 02:07 UTC by wackerow

- Removes hard-coded block explorer links, replaces with `.env` variable
- Removed `/tx/` from the end of the block explorer template URL in `.env.example` so this base link can be used for both tx and address lookups depending on the circumstance.

2021-08-09 14:25 UTC, pettinarip approved these changes
Nice!

2021-08-10 01:25 UTC, samajammin requested changes
Good call! One tiny change request 😄

2021-08-10 01:25 UTC, samajammin commented on vue-app/src/components/ProjectProfile.vue
> +  private get blockExplorer(): string {
For the sake of consistency let's go with `blockExplorerUrl` getter here where we construct the full URL in the getter.

2021-08-12 03:23 UTC, corwintines approved these changes
Nice 🚀

2021-08-13 16:13 UTC, samajammin approved these changes

2021-08-13 16:13 UTC, merged