No ability to exit out of MatchingFundsModal
ethereum/clrfund pull request #262
Opened 2021-08-14 17:32 UTC by corwintines

Notion: https://www.notion.so/August-11-Workday-d8b6aba59bff49e6898c7d5cda5eb85b
Fixes: https://github.com/ethereum/clrfund/issues/249

2021-08-16 19:35 UTC, pettinarip approved these changes
Great!

2021-08-18 20:19 UTC, samajammin commented on vue-app/src/views/ProjectList.vue
> +      return this.$modal.show(
I think this entire method can be removed? I don't believe `addMatchingFunds` is used here.

2021-08-18 20:25 UTC, samajammin requested changes
Looks mostly good!

One bug I noticed is on closing the modal, it keeps popping back up:

https://user-images.githubusercontent.com/8097623/129967395-1e15154b-dd89-4366-b1e5-dcd69ed962b9.mp4

I think we want to change the `closed` callback to not trigger the function again?

2021-08-18 20:26 UTC, samajammin commented
A couple comments to address. Also please fix conflicts 🙏 - thanks!

2021-08-18 22:07 UTC, corwintines commented
@samajammin good catch, thank you. I added a check on the closed callback to differentiate between if it was closing the modal vs going to the next step where the MatchingFundsModal should be open.

2021-08-18 22:48 UTC, samajammin requested changes
Thanks for the quick changes!

One more small issue I noticed:

https://user-images.githubusercontent.com/8097623/129981848-03cb67a4-935e-4393-810b-51874b708eb0.mp4

When we display the warning (i.e. user has insufficient funds) we should also disable the button to avoid this scary errors like this.

2021-08-19 03:35 UTC, wackerow approved these changes
nice, lookin good

2021-08-19 20:07 UTC, samajammin approved these changes

2021-08-19 20:07 UTC, merged