Fix text readability on transaction section page
ethereum/clrfund pull request #285
Opened 2021-08-20 15:38 UTC by Patil2099

Fixes #276 
I reduced the opacity of the image-wrapper which makes the text readable. 

![image](https://user-images.githubusercontent.com/35653876/130258070-9eff502c-b13a-4d72-8b07-d07bef242ba1.png)

2021-08-23 18:43 UTC, pettinarip commented
@Patil2099 Thanks for the contribution!!

I like the way you did it. My main concern is whether we need more opacity than `0.8`. I would use `0.6` but let's see what others think.

In either case, I'm ok with it.

2021-08-23 18:51 UTC, corwintines requested changes

2021-08-23 18:51 UTC, corwintines commented on vue-app/src/views/TransactionSuccess.vue
> +  opacity:0.8;
Thanks for the contribution @Patil2099!. I think this opacity would be better suited for the .money class. I think the money and confetti which use that class are what is causing this readability issue. If we apply the opacity to them, we can maintain the background this way. I think this also only needs to be done in the desktop size as well.

2021-08-30 16:51 UTC, corwintines commented
@samajammin since we are adding the gradient to the desktop view for transaction success: https://github.com/ethereum/clrfund/pull/304 was curious if we would still need this.

2021-09-09 02:34 UTC, samajammin commented
Hey @Patil2099! Thanks again for getting involved & for the PR. We haven't heard back from you about the requested changes & this issue has since been solved in #304.

Feel free to comment on another issue if you'd like to take a swing at one. Happy to work with you to ensure we can get it merged next time! Cheers.

2021-09-09 02:34 UTC, closed without merging