Refactored inline styling to classes [Fixes #261]
ethereum/clrfund pull request #288
Opened 2021-08-23 04:10 UTC by wackerow

- Extracts all instances of inline styling to CSS classes.
- Added a few recurrent single-purpose classes to `_theme.scss`
- Exceptions include dynamic styling that depends on props being passed to inline `style` attribute (ie: `IconStatus.vue` and `ProgressBar.vue`)

2021-08-23 19:38 UTC, corwintines approved these changes

2021-08-26 20:33 UTC, samajammin commented on vue-app/src/views/VerifyLanding.vue
> -      <div class="btn-container">
I think we still want this `btn-container` class.

Current `develop` preview:
![clr fund - clr fund 2021-08-26 at 1 31 35 PM](https://user-images.githubusercontent.com/8097623/131032059-ad655238-38ce-4f0a-bbb8-e105769d476d.jpg)

This branch's preview:
![clr fund - clr fund 2021-08-26 at 1 31 59 PM](https://user-images.githubusercontent.com/8097623/131032105-f7941dc9-fda9-4147-b499-6235045536b2.jpg)

2021-08-26 20:33 UTC, samajammin requested changes
Looks great for the most part! 💪 

See one comment - just some styling issues with the button layout on the verify landing page.

2021-08-27 15:14 UTC, wackerow commented on vue-app/src/views/VerifyLanding.vue
> -      <div class="btn-container">
Good catch 👍🏻

2021-08-27 15:15 UTC, wackerow commented
Fixed the button container, should be good now

2021-08-28 03:00 UTC, samajammin approved these changes

2021-08-28 03:00 UTC, merged