Generalize isRoundJoinPhase
ethereum/clrfund pull request #376
Opened 2021-09-15 19:09 UTC by corwintines

Fixes: https://github.com/ethereum/clrfund/issues/373

**What Changed**
- Check if recipient registry is optimistic, and if it is use challengePeriodDuration, otherwise use 0 when checking signup deadline

2021-09-16 20:10 UTC, pettinarip approved these changes
🚀

2021-09-21 17:00 UTC, samajammin commented on vue-app/src/store/index.ts
> +      process.env.VUE_APP_RECIPIENT_REGISTRY_TYPE === 'optimistic'
Let's use `recipientRegistryType` from /api/core.ts here.

2021-09-21 17:01 UTC, samajammin requested changes
Looks good! Minor change requested.

2021-09-21 21:54 UTC, samajammin approved these changes

2021-09-21 21:54 UTC, merged