Todo: RecipientSubmissionWidget isWaiting/isPending logic
ethereum/clrfund pull request #388
Opened 2021-09-24 18:19 UTC by corwintines

Fixes: https://github.com/ethereum/clrfund/issues/381

**What changed**
- Removed a bunch of unused code

2021-09-24 23:50 UTC, samajammin requested changes
This looks good 👍 but I feel like there's a missing state...

I just went through the flow on the preview deploy:
https://deploy-preview-388--eth2clrfund.netlify.app/#/join/project

After I submitted the submission tx (using MM), this is what displayed:
![clr fund - clr fund 2021-09-24 at 4 43 43 PM](https://user-images.githubusercontent.com/8097623/134749941-58710634-596e-47e1-8668-55f1f4b545a9.jpg)

It hung on "Check your wallet for a prompt" for a few seconds even though I had submitted the tx & the MM modal had been dismissed. I feel like we should have some sort of "Submitting..." state - is that possible with our current use of `waitForTransaction`?

At the end of the day Arbitrum should be much faster than Rinkeby here, so I'm not too worried about it. i.e. if you can't find a quick solution for this I'm ok to just accept as-is.

2021-09-25 17:33 UTC, corwintines commented
@samajammin will do some looking into this

2021-09-27 22:09 UTC, corwintines commented
@samajammin I think this would take looking into a bit of a refactor of waitForTransaction. Maybe out of scope for this ticket, but certainly something we could look at.

2021-09-28 20:17 UTC, samajammin approved these changes

2021-09-28 20:18 UTC, merged