Contribution success backdrop cutoff
ethereum/clrfund pull request #412
Opened 2021-09-29 20:51 UTC by corwintines

Fixes: https://github.com/ethereum/clrfund/issues/359

**What Changed**
- Change angle for linear gradient to prevent cutoff

2021-10-01 22:31 UTC, pettinarip requested changes
@corwintines I tested it but I still see the same issue (probably because I'm using a diff resolution screen). I understood your approach. Perhaps we can play more with it to prevent the problem in even bigger resolutions?

2021-10-06 14:39 UTC, pettinarip approved these changes
🚀

2021-10-06 15:12 UTC, samajammin commented
![Image 2021-10-06 at 8 12 32 AM](https://user-images.githubusercontent.com/8097623/136232076-49600813-7d28-4e89-9a4a-6b334f8aae8e.jpg)

LGTM!

2021-10-06 15:13 UTC, samajammin approved these changes

2021-10-06 15:13 UTC, merged