Revert optimistic changes
ethereum/clrfund pull request #449
Opened 2021-10-14 02:10 UTC by pettinarip

Tackle #432

- Reverted OptimisticRecipientReg contract changes.
- Made the `/recipients` page visible/accessible to everyone.
- Hide Approve/Register button when in challenge period and the user is not the owner
- Hide Reject/Challenge button when the user is not the owner
- Temporarily hide the "Remove" button from the Recipients view as it requires a base deposit (I think we can work on this after the merge).
- Added a generic `TransactionModal` component to see a tx progress.

2021-10-19 07:55 UTC, samajammin commented on vue-app/src/store/getters.ts
> +  isChallengePeriod: (_state: RootState, getters) => {
Won't `isChallengePeriod` vary by the recipient, since it is based on when each recipient applies?

2021-10-19 10:13 UTC, samajammin commented on vue-app/src/views/RecipientRegistry.vue
> +                    (isOwner || (!isOwner && !isChallengePeriod)) &&
Again I believe `isChallengePeriod` will vary be recipient depending on when they applied.

2021-10-19 10:14 UTC, samajammin requested changes
Let's chat through the `isChallengePeriod` - see my comments.

2021-10-19 11:32 UTC, pettinarip commented
> Let's chat through the `isChallengePeriod` - see my comments.

Good catch Sam, makes total sense. I made the fixes.

2021-10-26 19:26 UTC, samajammin approved these changes
Nice!

2021-10-26 19:26 UTC, merged